### ISSUE TITLE
Hook crashes the server

### ISSUE THREAD

**Issue by tarlepp** [mikermcneil/sails-hook-apianalytics#3]
Just noticed that hook crashes the server:

```
/home/wunder/projects/angular-sailsjs-boilerplate/backend/node_modules/sails-hook-apianalytics/index.js:42
            var numChars = inputs.method.length + inputs.path.length;
                                                             ^
TypeError: Cannot read property 'length' of undefined
    at /home/wunder/projects/angular-sailsjs-boilerplate/backend/node_modules/sails-hook-apianalytics/index.js:42:62
    at Object.defaults.apianalytics.onResponse (/home/wunder/projects/angular-sailsjs-boilerplate/backend/node_modules/sails-hook-apianalytics/index.js:54:13)
    at MockServerResponse.<anonymous> (/home/wunder/projects/angular-sailsjs-boilerplate/backend/node_modules/sails-hook-apianalytics/log-request.middleware.js:55:33)
    at MockServerResponse.g (events.js:180:16)
    at MockServerResponse.EventEmitter.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:356:12)
    at endWritable (_stream_writable.js:363:3)
    at MockServerResponse.Writable.end (_stream_writable.js:341:5)
    at MockServerResponse.res.end (/home/wunder/projects/angular-sailsjs-boilerplate/backend/node_modules/sails/lib/router/res.js:162:13)
    at writeend (/home/wunder/projects/angular-sailsjs-boilerplate/backend/node_modules/sails/node_modules/express/node_modules/connect/node_modules/express-session/index.js:207:14)
    at Object.onsave [as _onImmediate] (/home/wunder/projects/angular-sailsjs-boilerplate/backend/node_modules/sails/node_modules/express/node_modules/connect/node_modules/express-session/index.js:269:11)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by tarlepp** [comment]
Hmm, seems like ```req.path``` is ```undefined``` on socket requests.

Simple fix it to change ```req.path``` to ```req.url```

**Comment by mikermcneil** [comment]
@tarlepp ah, good catch- we should totally fix that in core sails though too...
