### ISSUE TITLE
E_VALIDATION on production mode

### ISSUE THREAD

**Issue by moisesrodriguez** [mikermcneil/sails-hook-apianalytics#7]
**Sails version:** 0.12.1
**Node version**: v4.4.5
**NPM version**: 2.15.5
**Operating system**: OS X El Capitan

When lifting sails on production mode, I get 

```
Error (E_VALIDATION) :: 2 attributes are invalid
     at WLValidationError.WLError (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/error/WLError.js:25:15)
     at new WLValidationError (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/error/WLValidationError.js:19:28)
     at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:47:23
     at allValidationsChecked (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:210:5)
     at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:52:16
     at Object.async.forEachOf.async.eachOf (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:236:30)
     at Object.async.forEach.async.each (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:209:22)
     at Validator.validate (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/core/validations.js:207:9)
     at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/lib/waterline/query/validate.js:42:25
     at /Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:718:13
     at Immediate.iterate [as _onImmediate] (/Users/moises/web/backend/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:262:13)
     at processImmediate [as _immediateCallback] (timers.js:383:17)
 Invalid attributes sent to RequestLog:
  • responseTime
    • `undefined` should be a integer (instead of "NaN", which is a number)
  • middlewareLatency
    • `undefined` should be a integer (instead of "NaN", which is a number)
```

It does not happen when I lift on development mode. Any ideas?

**Comment by jordanharris** [comment]
I'm getting the exact same issue

**Comment by CodeSchneider** [comment]
I am also having the exact same issue in production...

**Comment by mikermcneil** [comment]
That is really strange, this shouldn't even be talking to waterline anymore...  I wonder if there's some kind of interference going on w/ blueprints here?

**Comment by mikermcneil** [comment]
@CodeSchneider @jordanharris @moisesrodriguez hmm what's your blueprint config look like?  And is there anything going on in y'all's production config that could be related?

**Comment by moisesrodriguez** [comment]
@mikermcneil  This is how my blueprint config looks like

```
'use strict';
module.exports.blueprints = {
  actions: true,
  rest: true,
  shortcuts: false,
  prefix: '',
  pluralize: false,
  populate: false,
  autoWatch: true,
  mirror: true,
  defaultLimit: 4294967295
};
```

And I don't have anything on my production config different

**Comment by moisesrodriguez** [comment]
With latest release not having this issue anymore.
